export const articles = [
  {
    slug: 'how-to-decide-what-to-work-on',
    title: 'How to actually decide what to work on each morning',
    category: 'FOCUS',
    readTime: '5 min read',
    author: 'By the Daye team',
    preview: 'There is a particular kind of paralysis that hits most mornings. You sit down to work, you know you have things to do, and yet somehow twenty minutes pass and you have not started anything meaningful.',
    body: [
      { type: 'paragraph', text: 'There is a particular kind of paralysis that hits most mornings. You sit down to work, you know you have things to do, and yet somehow twenty minutes pass and you have not started anything meaningful. You have checked your email. You have looked at your calendar. You might have reorganised your task list. But you have not actually decided what matters today.' },
      { type: 'paragraph', text: 'This is not a laziness problem. It is a decision problem.' },
      { type: 'subheading', text: 'The cost of an undecided morning' },
      { type: 'paragraph', text: 'Every morning you spend not having a clear first task costs you more than just those minutes. Research on decision fatigue suggests that the quality of our decisions degrades throughout the day — which means the decisions you make at 9am are sharper than the ones you make at 3pm. If you spend your best decision-making hours deciding what to decide, you are burning your most valuable cognitive resource on the wrong thing.' },
      { type: 'paragraph', text: 'The irony is that most productivity advice makes this worse. More apps, more lists, more systems — all of which require more decisions before you can start working.' },
      { type: 'subheading', text: 'Why your to-do list is not helping' },
      { type: 'paragraph', text: 'A to-do list is a storage system, not a decision system. It holds everything you might do. It does not tell you what you should do today given who you are, how you feel, and what actually matters right now.' },
      { type: 'paragraph', text: 'This is why people with long, detailed, beautifully organised task lists still feel overwhelmed. The list has not made the decision. It has just made the pool of undecided things more visible.' },
      { type: 'subheading', text: 'The three inputs that actually matter' },
      { type: 'paragraph', text: 'After thinking about this for a long time, we believe there are really only three things that determine what you should work on today:' },
      { type: 'paragraph', text: 'Your energy. Not your ideal energy — your actual energy right now. A high-energy morning calls for different work than a low-energy one. Trying to do deep creative work on three hours of sleep is not discipline, it is poor planning.' },
      { type: 'paragraph', text: 'Your current pressure. What has a deadline today? What has been waiting too long? What will cost you most if it slips another day? Pressure is information — it tells you what the world is asking of you right now.' },
      { type: 'paragraph', text: 'Your longer goal. Not your quarterly objectives or your five-year plan, but the thing you are actually trying to move toward this month. Is it a promotion? A project launch? Getting on top of things? Your daily work should connect to something bigger, even if only loosely.' },
      { type: 'paragraph', text: 'When you cross-reference these three things, the answer usually becomes obvious. The problem is that most people never stop to do this explicitly. They just open their task list and pick something that looks manageable.' },
      { type: 'subheading', text: 'A better morning routine' },
      { type: 'paragraph', text: 'It does not have to be complicated. Before you start working, spend sixty seconds asking yourself three questions: How is my energy today? What is the most important thing that needs to happen? What am I ultimately working toward?' },
      { type: 'paragraph', text: 'The answers will usually point clearly to one or two things. Do those first. Everything else is secondary.' },
      { type: 'paragraph', text: 'This is the entire premise behind Daye. Not a more sophisticated task list — just a faster, cleaner way to make the decision you were going to make anyway, so you can get on with the actual work.' },
    ],
  },
  {
    slug: 'why-your-todo-list-is-failing-you',
    title: 'Why your to-do list is making you less productive',
    category: 'PRODUCTIVITY',
    readTime: '4 min read',
    author: 'By the Daye team',
    preview: 'If you have ever ended a day having crossed nothing off your list despite being busy the entire time, you already know something is wrong. The list was full. The day was full. And yet the right things did not get done.',
    body: [
      { type: 'paragraph', text: 'If you have ever ended a day having crossed nothing off your list despite being busy the entire time, you already know something is wrong. The list was full. The day was full. And yet somehow the right things did not get done.' },
      { type: 'paragraph', text: 'This is one of the most common experiences in modern work, and it is almost entirely caused by a misunderstanding of what a to-do list is actually for.' },
      { type: 'subheading', text: 'Lists are storage, not strategy' },
      { type: 'paragraph', text: 'A to-do list is extraordinarily good at one thing: holding information so your brain does not have to. This is genuinely useful. The cognitive load of trying to remember everything you need to do is exhausting, and offloading it to a list frees up mental space for actual thinking.' },
      { type: 'paragraph', text: 'But somewhere along the way, the list became the system. People started treating the act of adding things to a list as a form of progress. They started believing that a longer, more detailed, more beautifully organised list would somehow lead to better work.' },
      { type: 'paragraph', text: 'It does not. Because a list cannot make decisions. It can only present options.' },
      { type: 'subheading', text: 'The paradox of too many options' },
      { type: 'paragraph', text: 'There is substantial research showing that more options lead to worse decisions and lower satisfaction. This is true whether you are choosing a pension fund or deciding what to work on at 9am.' },
      { type: 'paragraph', text: 'When you open a task list with forty items on it, your brain is not presented with clarity — it is presented with a decision problem. Which of these forty things should I do right now? Which is most urgent? Which is most important? Are urgency and importance the same thing today? What did I promise to whom and by when?' },
      { type: 'paragraph', text: 'This is exhausting. And it happens before you have done a single minute of actual work.' },
      { type: 'subheading', text: 'What a list cannot tell you' },
      { type: 'paragraph', text: 'Your task list does not know how you feel today. It does not know that you slept badly and deep creative work is off the table. It does not know that your energy is unusually high and you should use it on the hardest thing rather than clearing easy tasks. It does not know that the presentation you have been avoiding for two weeks is now urgent because the meeting got moved to tomorrow.' },
      { type: 'paragraph', text: 'A list is static. Your day is dynamic. The mismatch between them is where productivity falls apart.' },
      { type: 'subheading', text: 'The one thing that fixes this' },
      { type: 'paragraph', text: 'The solution is not a better list. It is a daily decision about what the list means today — given your energy, your deadlines, and what you are ultimately trying to achieve.' },
      { type: 'paragraph', text: 'This does not have to be complicated or time-consuming. It is a sixty-second question: given everything I know about today, what are the one or two things that actually matter? Do those first. Let the list hold everything else until tomorrow.' },
      { type: 'paragraph', text: 'The list is still useful. It just needs to be in service of a decision, not a substitute for one.' },
    ],
  },
  {
    slug: 'sixty-second-morning-routine',
    title: 'The 60-second morning routine that actually changes your day',
    category: 'HABITS',
    readTime: '3 min read',
    author: 'By the Daye team',
    preview: 'Most morning routine advice is aspirational to the point of uselessness. Wake up at 5am. Meditate for twenty minutes. Journal three pages. By the time you have finished your morning routine it is lunchtime.',
    body: [
      { type: 'paragraph', text: 'Most morning routine advice is aspirational to the point of uselessness. Wake up at 5am. Meditate for twenty minutes. Journal three pages. Exercise for forty-five minutes. Cold shower. Read for an hour. By the time you have finished your morning routine it is lunchtime and you have not done any work.' },
      { type: 'paragraph', text: 'The morning routine that actually changes your day takes sixty seconds. And it has nothing to do with how early you wake up.' },
      { type: 'subheading', text: 'The only decision that matters in the morning' },
      { type: 'paragraph', text: 'Before you open your email, before you look at Slack, before you check anything — make one decision. What is the most important thing I need to do today?' },
      { type: 'paragraph', text: 'Not the most urgent. Not the easiest. The most important.' },
      { type: 'paragraph', text: 'This single decision, made before the noise of the day arrives, is worth more than any habit stack or productivity system. It gives your brain a target. It means that even if everything goes sideways — meetings overrun, requests pile up, energy dips — you know what success looks like today. One thing. If that gets done, the day was a good one.' },
      { type: 'subheading', text: 'Why timing matters' },
      { type: 'paragraph', text: 'The reason to do this in the morning rather than the night before is that your actual state matters. How you feel when you wake up, how well you slept, what happened yesterday — these things change what is realistic and what is wise to prioritise. Planning in the abstract the night before is useful but incomplete. The morning check-in with yourself is when you reconcile the plan with the reality.' },
      { type: 'subheading', text: 'The sixty seconds' },
      { type: 'paragraph', text: 'It goes like this. You sit down. You ask yourself three things:' },
      { type: 'paragraph', text: 'How is my energy today? Be honest. This determines whether you tackle the hardest thing first or build up to it.' },
      { type: 'paragraph', text: 'What has a deadline or is overdue? This is your constraint. It may override everything else.' },
      { type: 'paragraph', text: 'What am I working toward this month? This is your direction. It stops you from spending a high-energy day on low-value tasks just because they feel productive.' },
      { type: 'paragraph', text: 'Cross-reference those three answers. The right first task usually becomes obvious.' },
      { type: 'paragraph', text: 'Then start. Do not check email first. Do not warm up with easy tasks. Start with the thing you just decided matters most, while your energy and focus are at their best.' },
      { type: 'paragraph', text: 'That is the whole routine. Sixty seconds of honest self-assessment followed by one clear decision. Everything else in the day is easier once this is done.' },
    ],
  },
]
