export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  // Return realistic mocks in development to avoid API costs
  if (process.env.NODE_ENV === 'development') {
    await new Promise(r => setTimeout(r, 800))
    const type = req.body?.type || 'plan'

    if (type === 'tasks') {
      return res.status(200).json({
        result: JSON.stringify(['Complete the main project task', 'Review and respond to messages', 'Prepare for upcoming meetings']),
      })
    }

    if (type === 'reflection') {
      return res.status(200).json({
        result: JSON.stringify({
          summary: "It sounds like you're in a period of transition, holding both the uncertainty of not knowing what comes next and a genuine desire to find something that feels right for you.",
          goal: 'Finding clarity and a direction that feels authentically yours',
          blockers: ['Uncertainty about which path to take', 'Pressure to have it all figured out'],
          suggested_focus: 'Small exploratory actions that build momentum without pressure',
          encouragement: "You don't need to have it all figured out to start moving forward.",
        }),
      })
    }

    return res.status(200).json({
      result: JSON.stringify({
        priorities: [
          { task: 'Complete your most important task', subtitle: 'This is what moves the needle today — do it before anything else.' },
          { task: 'Review and respond to key messages', subtitle: 'Keep communication current so nothing blocks your progress.' },
        ],
        avoid: ['Unnecessary context-switching', 'Low-priority busywork'],
        timeSplit: [
          { time: '9-11am', task: 'Deep work on top priority' },
          { time: '11am-12pm', task: 'Clear inbox and messages' },
          { time: '12-1pm', task: 'Lunch break' },
          { time: '1-3pm', task: 'Project work' },
          { time: '3-4pm', task: 'Admin and review' },
          { time: '4-5pm', task: 'Plan tomorrow and close out' },
        ],
        why: "This is a mock plan — you're in development mode. Real plans are generated by Claude AI based on your energy, goals, and tasks.",
        dayLabel: 'Focus day',
        goalAlignment: 'Today moves you toward your goal',
        dayName: 'The Mock Day',
      }),
    })
  }

  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) {
    return res.status(500).json({ error: 'ANTHROPIC_API_KEY not configured' })
  }

  const { prompt, userId, isPro } = req.body || {}
  if (!prompt) {
    return res.status(400).json({ error: 'prompt is required' })
  }

  // Rate limit: free users max 3 plans per day
  if (userId && !isPro) {
    const today = new Date().toISOString().split('T')[0]
    const rateLimitKey = `rate_${userId}_${today}`
    // Use a simple in-memory store — works per serverless instance
    // For production persistence, this would use Redis or Supabase
    if (!global._planCounts) global._planCounts = {}
    const count = global._planCounts[rateLimitKey] || 0
    if (count >= 3) {
      return res.status(429).json({ error: 'Daily plan limit reached. Upgrade to Pro for unlimited plans.', rateLimited: true })
    }
    global._planCounts[rateLimitKey] = count + 1
  }

  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 1024,
        messages: [{ role: 'user', content: prompt }],
      }),
    })

    if (!response.ok) {
      const body = await response.text()
      return res.status(response.status).json({ error: `Claude API error: ${body}` })
    }

    const data = await response.json()
    const raw = data.content?.[0]?.text || ''
    const cleaned = raw
      .replace(/^```(?:json)?\s*/i, '')
      .replace(/\s*```\s*$/, '')
      .trim()

    return res.status(200).json({ result: cleaned })
  } catch (err) {
    return res.status(500).json({ error: err.message })
  }
}
